#!/bin/bash

# If destination path is not in mounts, suggest its mount and exit
nas_mnt_path="/mnt/nas/backup"
if [ -z "$(mount | grep $nas_mnt_path)" ] ; then
    >&2 echo "$nas_mnt_path not mounted"
    >&2 echo "Consider: sudo mount -t cifs -o vers=1.0,username=angel_be,uid=angel_be,gid=angel_be //192.168.0.50/backup $nas_mnt_path"
    exit 1
fi

# Source and destination are intentionally hardocded
source_path="/home/angel_be/Documentos"
destination_path="$nas_mnt_path/Documents"

# Logfile path
date_suffix=`date +%Y%m%d`
logfile_path="/tmp/backup_$date_suffix.log"

# Prepare rsync options
rsync_options=(
    -av --delete --itemize-changes --modify-window=5 --stats
    --include "Documentos*/***"
    --include "Dropbox/***"
    --exclude "*"
    --no-perms # Since NAS is mounted as a samba folder, trying to keep permissions is generating false positives
    "$@" # This is to allow other extra options to rsync such as --dry-run
)

echo "$ rsync ${rsync_options[@]} $source_path/ $destination_path > $logfile_path 2>&1" > $logfile_path
rsync "${rsync_options[@]}" "$source_path/" "$destination_path" >> "$logfile_path" 2>&1

# Push logfile to backup log folder
cp "$logfile_path" "$nas_mnt_path/backup_logs"
