#!/bin/bash -e

curr_path=`pwd`
my_mixes_path="$curr_path/my_mixes"

# First find occurrences of the files provided, to avoid repeated songs
for f in "$@"; do
    if [ ! -f "$f" ] ; then
        echo "ERROR: Unexistent file "$f""
	exit 1
    fi
    matches=`find "$my_mixes_path" -name "*$(basename "$f")*"`
    if [ ! -z "$matches" ] ; then
        echo "Song $(basename "$f") repeated in mix(es): "
	echo "$matches"
	echo ""
	while true ; do
            read -p "Continue anyway? [y/n] " yn
            case $yn in
                [Yy]* ) break ;;
		[Nn]* ) exit ;;
		*) echo "Invalid answer"
            esac
	done
    fi
done

# Create directory for new mix
last_mix=`find "$my_mixes_path" -maxdepth 1 -type d -name "fit_mix_*" | tail -n 1 | rev | cut -d'_' -f 1 | rev`
next_mix=$((last_mix+1))
new_mix_path="$my_mixes_path/fit_mix_$next_mix"
mkdir "$new_mix_path"

# Now speedup the files and move them to the desired location
for f in "$@"; do
    echo "Processing new song $(basename "$f")"
    ./speedup_one.sh "$f" "$new_mix_path"
done
touch "$new_mix_path/speeded_up_five"
echo "Mix $next_mix created successfully in $new_mix_path"
